stages:
  - install
  - build
  - test

include:
- template: Security/Dependency-Scanning.gitlab-ci.yml

default:
  image: node:latest

install_Dependencies:
  stage: install
  script:
    - npm install

build-frontend:
  stage: build
  script:
    - echo "Building frontend application"
    - npm install
    - npm run build

gemnasium-dependency_scanning:
    stage: test
    tags: [ saas-linux-large-amd64 ]
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
        - if: $CI_MERGE_REQUEST_IID
